foreach(path IN ITEMS ARCHIVE RUNTIME)
  if(NOT EXISTS "${${path}}")
    message(FATAL_ERROR "Missing compiler-owned ${path}: ${${path}}")
  endif()
  file(SHA256 "${${path}}" ${path}_SHA)
endforeach()
file(COPY_FILE "${RUNTIME}" "${OUTPUT}.runtime-install-image")
file(RPATH_REMOVE FILE "${OUTPUT}.runtime-install-image")
file(SHA256 "${OUTPUT}.runtime-install-image" INSTALLED_RUNTIME_SHA)
file(WRITE "${OUTPUT}" "#pragma once\n#define REGION_ARCHIVE_SHA \"${ARCHIVE_SHA}\"\n#define REGION_RUNTIME_SHA \"${RUNTIME_SHA}\"\n#define REGION_INSTALLED_RUNTIME_SHA \"${INSTALLED_RUNTIME_SHA}\"\n")
