#!/usr/bin/env python3
"""Compile-level tests for the explicitly labeled AST-JSON bootstrap frontend."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path


POSITIVE_CASES = {
    "host_only": 0,
    "gemm_capture": 1,
    "direct_qualified": 1,
    "two_sites": 2,
}

NEGATIVE_CASES = {
    "unqualified": "must be directly qualified",
    "indirect": "indirect or function-pointer",
    "template_call": "inside templates",
    "lambda_call": "inside lambdas",
    "macro_call": "generated by macros",
    "header_origin": "written directly in the input .mdsl file",
    "side_effect": "lhs must be a stable matrix lvalue",
    "output_alias": "output must not alias",
    "cuda_policy": "supports only target=cpu",
    "const_output": "deleted function 'out'",
    "temporary_output": "deleted function 'out'",
    "constexpr_call": "constexpr Matcore execution is not supported",
    "std_mdsl": "no member named 'mdsl' in namespace 'std'",
}


def extraction_command(extractor: Path, source: Path, output: Path) -> list[str]:
    return [
        str(extractor),
        "--input",
        source.as_posix(),
        "--ir-out",
        str(output),
        "--",
        "clang++",
        "-std=c++20",
        "-Icompiler/include",
        "-Icompiler/tests/frontend",
        source.as_posix(),
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--extractor", type=Path, required=True)
    arguments = parser.parse_args()

    repository = Path(__file__).resolve().parents[3]
    tests = Path("compiler/tests/frontend")
    failures: list[str] = []

    with tempfile.TemporaryDirectory(prefix="matcore-frontend-tests-") as temporary:
        output_root = Path(temporary)
        positive_bytes: dict[str, bytes] = {}

        for name, expected_operations in POSITIVE_CASES.items():
            source = tests / f"{name}.mdsl"
            output = output_root / f"{name}.json"
            completed = subprocess.run(
                extraction_command(arguments.extractor, source, output),
                cwd=repository,
                text=True,
                capture_output=True,
                check=False,
            )
            if completed.returncode != 0:
                failures.append(
                    f"positive {name} failed ({completed.returncode}):\n"
                    f"{completed.stderr}"
                )
                continue
            try:
                encoded = output.read_bytes()
                document = json.loads(encoded)
            except (OSError, json.JSONDecodeError) as error:
                failures.append(f"positive {name} emitted invalid JSON: {error}")
                continue
            positive_bytes[name] = encoded
            if document.get("schema") != "matcore.ir" or document.get("version") != 0:
                failures.append(f"positive {name} emitted the wrong schema/version")
            if document.get("producer") != "clang-ast-json-bootstrap-v0":
                failures.append(f"positive {name} did not label the bootstrap producer")
            operations = document.get("operations", [])
            if len(operations) != expected_operations:
                failures.append(
                    f"positive {name}: expected {expected_operations} operations, "
                    f"found {len(operations)}"
                )

        golden = repository / tests / "gemm_capture.golden.json"
        if positive_bytes.get("gemm_capture") != golden.read_bytes():
            failures.append("gemm_capture output differs from deterministic golden JSON")

        deterministic_output = output_root / "gemm_capture.second.json"
        deterministic = subprocess.run(
            extraction_command(
                arguments.extractor,
                tests / "gemm_capture.mdsl",
                deterministic_output,
            ),
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if deterministic.returncode != 0:
            failures.append(f"second deterministic extraction failed: {deterministic.stderr}")
        elif deterministic_output.read_bytes() != positive_bytes.get("gemm_capture"):
            failures.append("two identical extractions produced different JSON bytes")

        two_sites_path = output_root / "two_sites.json"
        if two_sites_path.exists():
            two_sites = json.loads(two_sites_path.read_text())
            identifiers = [operation["site_id"] for operation in two_sites["operations"]]
            if len(identifiers) != len(set(identifiers)):
                failures.append("two Matcore call sites did not receive distinct IDs")

        for name, expected_message in NEGATIVE_CASES.items():
            source = tests / f"{name}.mdsl"
            output = output_root / f"negative-{name}.json"
            completed = subprocess.run(
                extraction_command(arguments.extractor, source, output),
                cwd=repository,
                text=True,
                capture_output=True,
                check=False,
            )
            if completed.returncode == 0:
                failures.append(f"negative {name} unexpectedly succeeded")
                continue
            if expected_message not in completed.stderr:
                failures.append(
                    f"negative {name} lacked expected diagnostic "
                    f"{expected_message!r}:\n{completed.stderr}"
                )
            if ":" not in completed.stderr or "error:" not in completed.stderr:
                failures.append(f"negative {name} lacked a source error diagnostic")
            if output.exists():
                failures.append(f"negative {name} unexpectedly emitted an IR file")

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}", file=sys.stderr)
        print(f"frontend tests: {len(failures)} failure(s)", file=sys.stderr)
        return 1

    total = len(POSITIVE_CASES) + len(NEGATIVE_CASES) + 3
    print(f"frontend tests: {total} checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
