#!/usr/bin/env python3
"""Compile-level tests for the explicitly labeled AST-JSON bootstrap frontend."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path


POSITIVE_CASES = {
    "host_only": 0,
    "gemm_capture": 1,
    "direct_qualified": 1,
    "two_sites": 2,
}

NEGATIVE_CASES = {
    "unqualified": "must be directly qualified",
    "indirect": "indirect or function-pointer",
    "explicit_indirect": "indirect or function-pointer",
    "template_call": "inside templates",
    "lambda_call": "inside lambdas",
    "macro_call": "generated by macros",
    "header_origin": "written directly in the input .mdsl file",
    "side_effect": "lhs must be a stable matrix lvalue",
    "output_alias": "output must not alias",
    "cuda_policy": "supports only target=cpu",
    "policy_cast": "policy must be the default or an inline policy aggregate",
    "untrusted_header": "compiler's trusted <matcore/mdsl.h> header",
    "const_output": "deleted function 'out'",
    "temporary_output": "deleted function 'out'",
    "constexpr_call": "constexpr Matcore execution is not supported",
    "std_mdsl": "no member named 'mdsl' in namespace 'std'",
}


def extraction_command(extractor: Path, source: Path, output: Path) -> list[str]:
    return [
        str(extractor),
        "--input",
        source.as_posix(),
        "--ir-out",
        str(output),
        "--",
        "clang++",
        "-std=c++20",
        "-Icompiler/include",
        "-Icompiler/tests/frontend",
        source.as_posix(),
    ]


def generation_command(
    extractor: Path, source: Path, output_root: Path, stem: str
) -> tuple[list[str], dict[str, Path]]:
    outputs = {
        "ir": output_root / f"{stem}.matcore.json",
        "host": output_root / f"{stem}.host.cpp",
        "sites": output_root / f"{stem}.sites.h",
        "stubs": output_root / f"{stem}.stubs.cpp",
        "backend": output_root / f"{stem}.backend.cpp",
    }
    command = extraction_command(extractor, source, outputs["ir"])
    separator = command.index("--")
    command[separator:separator] = [
        "--rewrite-out",
        str(outputs["host"]),
        "--sites-out",
        str(outputs["sites"]),
        "--stubs-out",
        str(outputs["stubs"]),
        "--backend-out",
        str(outputs["backend"]),
    ]
    return command, outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--extractor", type=Path, required=True)
    arguments = parser.parse_args()

    repository = Path(__file__).resolve().parents[3]
    tests = Path("compiler/tests/frontend")
    failures: list[str] = []

    with tempfile.TemporaryDirectory(prefix="matcore-frontend-tests-") as temporary:
        output_root = Path(temporary)
        positive_bytes: dict[str, bytes] = {}

        for name, expected_operations in POSITIVE_CASES.items():
            source = tests / f"{name}.mdsl"
            output = output_root / f"{name}.json"
            completed = subprocess.run(
                extraction_command(arguments.extractor, source, output),
                cwd=repository,
                text=True,
                capture_output=True,
                check=False,
            )
            if completed.returncode != 0:
                failures.append(
                    f"positive {name} failed ({completed.returncode}):\n"
                    f"{completed.stderr}"
                )
                continue
            try:
                encoded = output.read_bytes()
                document = json.loads(encoded)
            except (OSError, json.JSONDecodeError) as error:
                failures.append(f"positive {name} emitted invalid JSON: {error}")
                continue
            positive_bytes[name] = encoded
            if document.get("schema") != "matcore.ir" or document.get("version") != 0:
                failures.append(f"positive {name} emitted the wrong schema/version")
            if document.get("producer") != "clang-ast-json-bootstrap-v0":
                failures.append(f"positive {name} did not label the bootstrap producer")
            operations = document.get("operations", [])
            if len(operations) != expected_operations:
                failures.append(
                    f"positive {name}: expected {expected_operations} operations, "
                    f"found {len(operations)}"
                )

        golden = repository / tests / "gemm_capture.golden.json"
        if positive_bytes.get("gemm_capture") != golden.read_bytes():
            failures.append("gemm_capture output differs from deterministic golden JSON")

        verified = subprocess.run(
            [str(arguments.extractor), "--verify-ir", str(golden)],
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if verified.returncode != 0 or "verified Matcore IR v0" not in verified.stdout:
            failures.append(f"valid serialized IR did not verify: {verified.stderr}")

        malformed_path = output_root / "malformed.json"
        malformed_path.write_text("{broken\n")
        malformed = subprocess.run(
            [str(arguments.extractor), "--verify-ir", str(malformed_path)],
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if malformed.returncode == 0 or "malformed JSON" not in malformed.stderr:
            failures.append("malformed serialized IR was not rejected cleanly")

        schema_path = output_root / "schema-mismatch.json"
        schema_document = json.loads(golden.read_text())
        schema_document["schema"] = "matcore.ir.future"
        schema_path.write_text(json.dumps(schema_document))
        schema = subprocess.run(
            [str(arguments.extractor), "--verify-ir", str(schema_path)],
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if schema.returncode == 0 or "unsupported Matcore IR schema" not in schema.stderr:
            failures.append("schema-mismatched serialized IR was not rejected cleanly")

        version_path = output_root / "version-mismatch.json"
        version_document = json.loads(golden.read_text())
        version_document["version"] = 1
        version_path.write_text(json.dumps(version_document))
        versioned = subprocess.run(
            [str(arguments.extractor), "--verify-ir", str(version_path)],
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if versioned.returncode == 0 or "expected version 0" not in versioned.stderr:
            failures.append("version-mismatched serialized IR was not rejected cleanly")

        semantic_mutations = {
            "missing-shape": lambda document: document["operations"][0]["output"].pop(
                "shape"
            ),
            "wrong-strides": lambda document: document["operations"][0]["operands"][
                0
            ].__setitem__("strides", ["1", "dynamic-columns"]),
            "missing-aliases": lambda document: document["operations"][0].pop(
                "alias_requirements"
            ),
            "missing-effects": lambda document: document["operations"][0].pop(
                "effects"
            ),
            "invalid-site-id": lambda document: document["operations"][0].__setitem__(
                "site_id", "not-valid!"
            ),
        }
        for mutation_name, mutate in semantic_mutations.items():
            mutated_document = json.loads(golden.read_text())
            mutate(mutated_document)
            mutated_path = output_root / f"{mutation_name}.json"
            mutated_path.write_text(json.dumps(mutated_document))
            mutated = subprocess.run(
                [str(arguments.extractor), "--verify-ir", str(mutated_path)],
                cwd=repository,
                text=True,
                capture_output=True,
                check=False,
            )
            if mutated.returncode == 0:
                failures.append(f"IR verifier accepted semantic mutation {mutation_name}")

        changing_source = output_root / "changing.mdsl"
        changing_source.write_bytes((repository / tests / "gemm_capture.mdsl").read_bytes())
        changing_compiler = output_root / "changing-clang++"
        changing_compiler.write_text(
            "#!/bin/sh\n"
            "printf '\\n// concurrent edit\\n' >> \"$MDSLC_RACE_SOURCE\"\n"
            "exec /usr/bin/clang++-21 \"$@\"\n",
            encoding="utf-8",
        )
        changing_compiler.chmod(0o755)
        changing_command = extraction_command(
            arguments.extractor, changing_source, output_root / "changing.json"
        )
        changing_command[changing_command.index("--"):changing_command.index("--")] = [
            "--clang",
            str(changing_compiler),
        ]
        del changing_command[changing_command.index("--") + 1]
        changed = subprocess.run(
            changing_command,
            cwd=repository,
            env={**os.environ, "MDSLC_RACE_SOURCE": str(changing_source)},
            text=True,
            capture_output=True,
            check=False,
        )
        if changed.returncode == 0 or "changed while Clang parsed it" not in changed.stderr:
            failures.append("concurrently changed source was not rejected cleanly")

        deterministic_output = output_root / "gemm_capture.second.json"
        deterministic = subprocess.run(
            extraction_command(
                arguments.extractor,
                tests / "gemm_capture.mdsl",
                deterministic_output,
            ),
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if deterministic.returncode != 0:
            failures.append(f"second deterministic extraction failed: {deterministic.stderr}")
        elif deterministic_output.read_bytes() != positive_bytes.get("gemm_capture"):
            failures.append("two identical extractions produced different JSON bytes")

        absolute_output = output_root / "gemm_capture.absolute.json"
        absolute_source = (repository / tests / "gemm_capture.mdsl").resolve()
        absolute = subprocess.run(
            extraction_command(arguments.extractor, absolute_source, absolute_output),
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if absolute.returncode != 0:
            failures.append(f"absolute-path extraction failed: {absolute.stderr}")
        else:
            relative_site = json.loads(positive_bytes["gemm_capture"])["operations"][0][
                "site_id"
            ]
            absolute_site = json.loads(absolute_output.read_text())["operations"][0][
                "site_id"
            ]
            if relative_site != absolute_site:
                failures.append(
                    "relative and absolute spellings of one source changed its site ID"
                )

        two_sites_path = output_root / "two_sites.json"
        if two_sites_path.exists():
            two_sites = json.loads(two_sites_path.read_text())
            identifiers = [operation["site_id"] for operation in two_sites["operations"]]
            if len(identifiers) != len(set(identifiers)):
                failures.append("two Matcore call sites did not receive distinct IDs")

        multi_tu_root = output_root / "multi-tu"
        multi_tu_objects: list[Path] = []
        multi_tu_sites: list[str] = []
        for label, function_name in (("left", "entry_left"), ("right", "entry_rght")):
            work = multi_tu_root / label
            source_dir = work / "src"
            generated_dir = work / "generated"
            source_dir.mkdir(parents=True)
            generated_dir.mkdir()
            source = source_dir / "same.mdsl"
            source.write_text(
                "#include <matcore/mdsl.h>\n\n"
                "namespace md = matcore::mdsl;\n\n"
                f"[[maybe_unused]] static void {function_name}("
                "md::matrix_view &C, md::matrix_view &A, md::matrix_view &B) {\n"
                "  md::gemm(md::out(C), A, B, "
                "md::policy{.target = md::target::cpu, "
                ".fallback = md::fallback::error});\n"
                "}\n",
                encoding="utf-8",
            )
            outputs = {
                "ir": generated_dir / "same.json",
                "host": generated_dir / "same.host.cpp",
                "sites": generated_dir / "same.sites.h",
                "stubs": generated_dir / "same.stubs.cpp",
                "backend": generated_dir / "same.backend.cpp",
            }
            command = [
                str(arguments.extractor),
                "--input",
                "src/same.mdsl",
                "--ir-out",
                str(outputs["ir"]),
                "--rewrite-out",
                str(outputs["host"]),
                "--sites-out",
                str(outputs["sites"]),
                "--stubs-out",
                str(outputs["stubs"]),
                "--backend-out",
                str(outputs["backend"]),
                "--",
                "clang++",
                "-std=c++20",
                f"-I{repository / 'compiler/include'}",
                "src/same.mdsl",
            ]
            extracted = subprocess.run(
                command, cwd=work, text=True, capture_output=True, check=False
            )
            if extracted.returncode != 0:
                failures.append(
                    f"multi-TU {label} extraction failed: {extracted.stderr}"
                )
                continue
            multi_tu_sites.append(
                json.loads(outputs["ir"].read_text())["operations"][0]["site_id"]
            )
            objects: list[Path] = []
            for kind in ("host", "stubs", "backend"):
                object_path = generated_dir / f"same.{kind}.o"
                compiled = subprocess.run(
                    [
                        "/usr/bin/clang++-21",
                        "-std=c++20",
                        f"-I{repository / 'compiler/include'}",
                        f"-I{generated_dir}",
                        "-c",
                        str(outputs[kind]),
                        "-o",
                        str(object_path),
                    ],
                    cwd=work,
                    text=True,
                    capture_output=True,
                    check=False,
                )
                if compiled.returncode != 0:
                    failures.append(
                        f"multi-TU {label} {kind} compile failed: {compiled.stderr}"
                    )
                    break
                objects.append(object_path)
            if len(objects) == 3:
                combined_object = generated_dir / "same.o"
                combined = subprocess.run(
                    [
                        "/usr/bin/clang++-21",
                        "-r",
                        *(str(path) for path in objects),
                        "-o",
                        str(combined_object),
                    ],
                    cwd=work,
                    text=True,
                    capture_output=True,
                    check=False,
                )
                if combined.returncode != 0:
                    failures.append(
                        f"multi-TU {label} partial link failed: {combined.stderr}"
                    )
                else:
                    multi_tu_objects.append(combined_object)
        if len(multi_tu_sites) == 2 and multi_tu_sites[0] == multi_tu_sites[1]:
            failures.append("same-spelled sources in distinct directories collided")
        if len(multi_tu_objects) == 2:
            linked = subprocess.run(
                [
                    "/usr/bin/clang++-21",
                    "-r",
                    *(str(path) for path in multi_tu_objects),
                    "-o",
                    str(multi_tu_root / "combined.o"),
                ],
                text=True,
                capture_output=True,
                check=False,
            )
            if linked.returncode != 0:
                failures.append(
                    f"distinct MDSLC translation units did not co-link: {linked.stderr}"
                )

        generation, generated = generation_command(
            arguments.extractor,
            tests / "gemm_capture.mdsl",
            output_root,
            "gemm_capture",
        )
        completed = subprocess.run(
            generation,
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if completed.returncode != 0:
            failures.append(f"rewrite generation failed: {completed.stderr}")
        else:
            golden_artifacts = {
                "host": tests / "gemm_capture.host.golden.cpp",
                "sites": tests / "gemm_capture.sites.golden.h",
                "stubs": tests / "gemm_capture.stubs.golden.cpp",
                "backend": tests / "gemm_capture.backend.golden.cpp",
            }
            for kind, golden_path in golden_artifacts.items():
                if generated[kind].read_bytes() != (repository / golden_path).read_bytes():
                    failures.append(f"generated {kind} differs from its golden file")

            objects: list[Path] = []
            for kind in ("host", "stubs", "backend"):
                object_path = output_root / f"gemm_capture.{kind}.o"
                compile_command = [
                    "/usr/bin/clang++-21",
                    "-std=c++20",
                    "-Wall",
                    "-Wextra",
                    "-Wpedantic",
                    "-Werror",
                    "-Icompiler/include",
                    f"-I{output_root}",
                    "-c",
                    str(generated[kind]),
                    "-o",
                    str(object_path),
                ]
                compiled = subprocess.run(
                    compile_command,
                    cwd=repository,
                    text=True,
                    capture_output=True,
                    check=False,
                )
                if compiled.returncode != 0:
                    failures.append(
                        f"generated {kind} failed strict compilation:\n"
                        f"{compiled.stderr}"
                    )
                else:
                    objects.append(object_path)
            if len(objects) == 3:
                combined = subprocess.run(
                    [
                        "/usr/bin/clang++-21",
                        "-r",
                        *(str(path) for path in objects),
                        "-o",
                        str(output_root / "gemm_capture.combined.o"),
                    ],
                    cwd=repository,
                    text=True,
                    capture_output=True,
                    check=False,
                )
                if combined.returncode != 0:
                    failures.append(
                        f"generated objects failed relocatable link:\n"
                        f"{combined.stderr}"
                    )

        second_root = output_root / "second"
        second_root.mkdir()
        second_generation, second_generated = generation_command(
            arguments.extractor,
            tests / "gemm_capture.mdsl",
            second_root,
            "gemm_capture",
        )
        repeated = subprocess.run(
            second_generation,
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if repeated.returncode != 0:
            failures.append(f"repeated rewrite generation failed: {repeated.stderr}")
        elif any(
            generated[kind].read_bytes() != second_generated[kind].read_bytes()
            for kind in generated
        ):
            failures.append("repeated rewrite generation was not byte deterministic")

        empty_generation, empty_generated = generation_command(
            arguments.extractor,
            tests / "host_only.mdsl",
            output_root,
            "host_only",
        )
        empty = subprocess.run(
            empty_generation,
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if empty.returncode != 0:
            failures.append(f"zero-operation generation failed: {empty.stderr}")
        elif not all(path.exists() and path.stat().st_size > 0 for path in empty_generated.values()):
            failures.append("zero-operation generation did not emit all valid files")

        partial_output = output_root / "partial.host.cpp"
        partial_command = extraction_command(
            arguments.extractor,
            tests / "host_only.mdsl",
            output_root / "partial.json",
        )
        partial_command[partial_command.index("--"):partial_command.index("--")] = [
            "--rewrite-out",
            str(partial_output),
        ]
        partial = subprocess.run(
            partial_command,
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if partial.returncode == 0 or "must be supplied together" not in partial.stderr:
            failures.append("partial generated-output option group was not rejected")

        for name, expected_message in NEGATIVE_CASES.items():
            source = tests / f"{name}.mdsl"
            output = output_root / f"negative-{name}.json"
            completed = subprocess.run(
                extraction_command(arguments.extractor, source, output),
                cwd=repository,
                text=True,
                capture_output=True,
                check=False,
            )
            if completed.returncode == 0:
                failures.append(f"negative {name} unexpectedly succeeded")
                continue
            if expected_message not in completed.stderr:
                failures.append(
                    f"negative {name} lacked expected diagnostic "
                    f"{expected_message!r}:\n{completed.stderr}"
                )
            if ":" not in completed.stderr or "error:" not in completed.stderr:
                failures.append(f"negative {name} lacked a source error diagnostic")
            if output.exists():
                failures.append(f"negative {name} unexpectedly emitted an IR file")

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}", file=sys.stderr)
        print(f"frontend tests: {len(failures)} failure(s)", file=sys.stderr)
        return 1

    total = len(POSITIVE_CASES) + len(NEGATIVE_CASES) + 24
    print(f"frontend tests: {total} checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
