# Build input only; machine gate must have succeeded immediately before this.
if(NOT TARGET_KIND MATCHES "^(nvvm|rocdl)$" OR NOT EXISTS "${IMAGE}.object-contract")
  message(FATAL_ERROR "Missing checked built-in GPU pair image")
endif()
file(SIZE "${IMAGE}" size)
if(size LESS 64 OR size GREATER 67108864)
  message(FATAL_ERROR "Invalid bounded GPU pair image size")
endif()
file(SHA256 "${IMAGE}" sha)
file(READ "${IMAGE}.object-contract" contract)
if(NOT contract MATCHES "image_sha256=${sha}\n" OR NOT contract MATCHES "target=${TARGET_KIND}\n")
  message(FATAL_ERROR "GPU pair image changed after machine gate")
endif()
file(READ "${IMAGE}" bytes HEX)
string(REGEX REPLACE "(..)" "0x\\1," bytes "${bytes}")
file(WRITE "${OUTPUT}" "#include <cstddef>\nnamespace matcore::mdslc::runtime::closed_host_v1::detail {\nalignas(64) extern const unsigned char mdslc_${TARGET_KIND}_fused_pair_image_v1[] = {${bytes}};\nextern const std::size_t mdslc_${TARGET_KIND}_fused_pair_image_v1_size = ${size};\n}\n")
file(WRITE "${OUTPUT}.manifest" "target=${TARGET_KIND}\npair_sha256=${sha}\npair_bytes=${size}\nsource_authority=none_build_issued_primitive_only\n")
