# Compiler-build input only. These bytes never come from mdslc-region source
# options or a runtime module path. The driver seals the resulting private DSO.
if(NOT TARGET_KIND MATCHES "^(nvvm|rocdl)$")
  message(FATAL_ERROR "Unknown private GPU image target")
endif()
set(contents "#include \"closed_gpu_images_v1.h\"\nnamespace matcore::mdslc::runtime::closed_host_v1::detail {\n")
set(manifest "target=${TARGET_KIND}\n")
foreach(stage IN ITEMS fill gemm)
  string(TOUPPER "${stage}" upper)
  file(SIZE "${${upper}_IMAGE}" size)
  if(size LESS 64 OR size GREATER 67108864)
    message(FATAL_ERROR "Invalid bounded GPU image size")
  endif()
  file(READ "${${upper}_IMAGE}" bytes HEX)
  if(NOT bytes MATCHES "^7f454c46")
    message(FATAL_ERROR "GPU build image is not an ELF artifact")
  endif()
  file(SHA256 "${${upper}_IMAGE}" sha)
  string(APPEND manifest "${stage}_sha256=${sha}\n${stage}_bytes=${size}\n")
  string(REGEX REPLACE "(..)" "0x\\1," bytes "${bytes}")
  string(APPEND contents "alignas(64) const unsigned char mdslc_${TARGET_KIND}_${stage}_image_v1[] = {${bytes}};\nconst std::size_t mdslc_${TARGET_KIND}_${stage}_image_v1_size = ${size};\n")
endforeach()
string(APPEND contents "}\n")
file(WRITE "${OUTPUT}" "${contents}")
file(WRITE "${OUTPUT}.manifest" "${manifest}")
