# Mandatory actual image gate; no Python/runtime importer/authority dependency.
set(kernel __matcore_strict_fused_gemm_f32_v1_kernel)
function(inspect output)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE text ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "GPU pair inspection failed: ${ARGN}: ${error}")
  endif()
  set(${output} "${text}" PARENT_SCOPE)
endfunction()
if(NOT TARGET_KIND MATCHES "^(nvvm|rocdl)$")
  message(FATAL_ERROR "Unknown GPU pair image target")
endif()
file(READ "${IMAGE}" header HEX LIMIT 64)
if(NOT header MATCHES "^7f454c46020101")
  message(FATAL_ERROR "GPU pair image is not ELF64 little-endian")
endif()
string(SUBSTRING "${header}" 32 8 type_machine)
string(SUBSTRING "${header}" 96 8 flags)
if(TARGET_KIND STREQUAL "nvvm")
  string(SUBSTRING "${flags}" 2 2 sm)
  if(NOT type_machine STREQUAL "0200be00" OR NOT sm STREQUAL "59")
    message(FATAL_ERROR "GPU pair image is not sm89 CUDA executable")
  endif()
else()
  string(SUBSTRING "${flags}" 0 2 isa)
  if(NOT type_machine STREQUAL "0300e000" OR NOT isa STREQUAL "43")
    message(FATAL_ERROR "GPU pair image is not gfx1150 shared code object")
  endif()
endif()
inspect(imports "${NM}" --undefined-only "${IMAGE}")
string(STRIP "${imports}" imports)
if(NOT imports STREQUAL "")
  message(FATAL_ERROR "GPU pair image acquired imports: ${imports}")
endif()
inspect(symbols "${NM}" --defined-only "${IMAGE}")
string(REGEX MATCHALL "[0-9a-fA-F]+ T [^\n]+" functions "${symbols}")
list(LENGTH functions function_count)
if(NOT function_count EQUAL 1 OR NOT functions MATCHES " T ${kernel}$")
  message(FATAL_ERROR "GPU pair image executable exports changed: ${functions}")
endif()
if(TARGET_KIND STREQUAL "nvvm")
  inspect(assembly "${CUOBJDUMP}" --dump-sass "${IMAGE}")
  inspect(metadata "${CUOBJDUMP}" --dump-elf "${IMAGE}")
  if(NOT assembly MATCHES "sm_89" OR assembly MATCHES "(FFMA|HFMA|HMMA|IMMA|MMA|[.]FTZ)" OR
     NOT assembly MATCHES "FMUL " OR NOT assembly MATCHES "FADD ")
    message(FATAL_ERROR "NVVM pair lost separate f32/gradual/import-free arithmetic")
  endif()
  # Pinned ptxas emits CALL.REL.NOINC as a conditional transfer to EXIT in this
  # same sole kernel, with zero stack. This is NOT a blanket machine-call-free
  # claim or permission for arbitrary device calls/imports.
  string(REGEX MATCHALL "[^\n]*CALL[^\n]*" calls "${assembly}")
  foreach(call IN LISTS calls)
    if(NOT call MATCHES "CALL[.]REL[.]NOINC +0x([0-9a-f]+) +;")
      message(FATAL_ERROR "NVVM pair acquired an unknown machine call")
    endif()
    set(exit_target "${CMAKE_MATCH_1}")
    if(NOT assembly MATCHES "/[*]0*${exit_target}[*]/[ \t]+EXIT[ \t;]")
      message(FATAL_ERROR "NVVM relative NOINC transfer does not target same-kernel EXIT")
    endif()
  endforeach()
  string(REGEX MATCHALL "Ordinal : 0x[0-9a-fA-F]+[ \t]+Offset  : 0x[0-9a-fA-F]+[ \t]+Size    : 0x8([ \t\r\n]|$)" parameters "${metadata}")
  list(LENGTH parameters parameter_count)
  if(NOT parameter_count EQUAL 35 OR NOT metadata MATCHES "EIATTR_CBANK_PARAM_SIZE[^<]*Value:[ \t]*0x118([ \t\r\n]|$)" OR
     NOT metadata MATCHES "frame size: 0x0([ \t\r\n]|$)" OR NOT metadata MATCHES "min stack size: 0x0([ \t\r\n]|$)")
    message(FATAL_ERROR "NVVM pair35x8-byte ABI or zero stack contract changed")
  endif()
  foreach(index RANGE 0 34)
    math(EXPR ordinal "${index}" OUTPUT_FORMAT HEXADECIMAL)
    math(EXPR offset "${index}*8" OUTPUT_FORMAT HEXADECIMAL)
    if(NOT parameters MATCHES "Ordinal : ${ordinal}[ \t]+Offset  : ${offset}[ \t]+Size    : 0x8([ \t\r\n]|$)")
      message(FATAL_ERROR "NVVM pair field${index} changed offset/size")
    endif()
  endforeach()
else()
  inspect(assembly "${OBJDUMP}" -d "${IMAGE}")
  inspect(metadata "${READELF}" --notes "${IMAGE}")
  inspect(rodata "${READELF}" --hex-dump=.rodata "${IMAGE}")
  inspect(dynamic_symbols "${READELF}" --dyn-syms --wide "${IMAGE}")
  inspect(sections "${READELF}" --section-headers --wide "${IMAGE}")
  if(NOT assembly MATCHES "file format elf64-amdgpu" OR assembly MATCHES "v_(fma|mad|mfma|wmma)" OR
     NOT assembly MATCHES "v_mul_f32" OR NOT assembly MATCHES "v_add_f32")
    message(FATAL_ERROR "ROCDL pair lost separate f32 arithmetic")
  endif()
  string(REPLACE "\n" ";" rows "${rodata}")
  set(descriptor)
  set(descriptor_address "")
  foreach(row IN LISTS rows)
    if(row MATCHES "^0x[0-9a-f]+ ([0-9a-f]+) +([0-9a-f]+) +([0-9a-f]+) +([0-9a-f]+) ")
      string(APPEND descriptor "${CMAKE_MATCH_1}${CMAKE_MATCH_2}${CMAKE_MATCH_3}${CMAKE_MATCH_4}")
      if(descriptor_address STREQUAL "")
        string(REGEX MATCH "^0x([0-9a-f]+)" first_address "${row}")
        set(descriptor_address "${CMAKE_MATCH_1}")
      endif()
    endif()
  endforeach()
  string(LENGTH "${descriptor}" descriptor_length)
  if(NOT descriptor_length EQUAL 128 OR NOT descriptor MATCHES "^000000000000000018020000" OR
     NOT metadata MATCHES "[.]max_flat_workgroup_size: 1([ \t\r\n]|$)" OR
     NOT metadata MATCHES "[.]sgpr_spill_count: 0([ \t\r\n]|$)" OR NOT metadata MATCHES "[.]vgpr_spill_count: 0([ \t\r\n]|$)" OR
     NOT metadata MATCHES "[.]uses_dynamic_stack: false([ \t\r\n]|$)")
    message(FATAL_ERROR "ROCDL pair exact descriptor/536-byte args/private/group/workgroup/spill contract changed")
  endif()
  if(NOT dynamic_symbols MATCHES "[0-9]+: +([0-9a-f]+) +64 OBJECT +GLOBAL +DEFAULT +([0-9]+) +${kernel}[.]kd([ \t\r\n]|$)")
    message(FATAL_ERROR "ROCDL pair lacks exact exported64-byte kernel descriptor")
  endif()
  set(symbol_address "${CMAKE_MATCH_1}")
  set(symbol_section "${CMAKE_MATCH_2}")
  math(EXPR descriptor_address "0x${descriptor_address}")
  math(EXPR symbol_address "0x${symbol_address}")
  if(NOT descriptor_address EQUAL symbol_address OR
     NOT sections MATCHES "\\[ *${symbol_section}\\] +[.]rodata +PROGBITS ")
    message(FATAL_ERROR "ROCDL pair kernel descriptor symbol does not bind inspected .rodata")
  endif()
  string(REGEX MATCHALL "[.]offset: +[0-9]+[ \t\r\n]+[.]size: +[0-9]+([ \t\r\n]|$)" parameters "${metadata}")
  list(LENGTH parameters parameter_count)
  if(parameter_count LESS 35)
    message(FATAL_ERROR "ROCDL pair35 explicit argument fields are missing")
  endif()
  foreach(index RANGE 0 34)
    list(GET parameters ${index} parameter)
    math(EXPR offset "${index}*8")
    if(NOT parameter MATCHES "[.]offset: +${offset}[ \t\r\n]+[.]size: +8([ \t\r\n]|$)")
      message(FATAL_ERROR "ROCDL pair field${index} offset/size changed")
    endif()
  endforeach()
  string(REGEX MATCHALL "[.]value_kind: +[a-z0-9_]+" kinds "${metadata}")
  list(LENGTH kinds kind_count)
  if(NOT kind_count EQUAL parameter_count)
    message(FATAL_ERROR "ROCDL pair argument metadata entry count changed")
  endif()
  math(EXPR last_kind "${kind_count}-1")
  foreach(index RANGE 0 ${last_kind})
    list(GET kinds ${index} kind)
    if(index LESS 35)
      math(EXPR field "${index}%7")
      if(field LESS 2)
        set(expected_kind global_buffer)
      else()
        set(expected_kind by_value)
      endif()
      if(NOT kind MATCHES "[.]value_kind: +${expected_kind}$")
        message(FATAL_ERROR "ROCDL pair field${index} pointer/integer kind changed")
      endif()
    elseif(NOT kind MATCHES "[.]value_kind: +hidden_")
      message(FATAL_ERROR "ROCDL pair acquired an extra explicit argument")
    endif()
  endforeach()
  # AMDHSAKernelDescriptor.h pinned21.1.8: RSRC1 offset48 bytes;
  # f32 round bits12..13=0, denorm bits16..17=3, IEEE bit23=1.
  string(SUBSTRING "${descriptor}" 96 2 b0)
  string(SUBSTRING "${descriptor}" 98 2 b1)
  string(SUBSTRING "${descriptor}" 100 2 b2)
  string(SUBSTRING "${descriptor}" 102 2 b3)
  math(EXPR rsrc1 "0x${b3}${b2}${b1}${b0}")
  math(EXPR round "(${rsrc1}>>12)&3")
  math(EXPR denorm "(${rsrc1}>>16)&3")
  math(EXPR ieee "(${rsrc1}>>23)&1")
  if(NOT round EQUAL 0 OR NOT denorm EQUAL 3 OR NOT ieee EQUAL 1)
    message(FATAL_ERROR "ROCDL pair f32 FP mode is not nearest/gradual/IEEE")
  endif()
endif()
file(SHA256 "${IMAGE}" sha)
file(WRITE "${IMAGE}.assembly" "${assembly}")
file(WRITE "${IMAGE}.object-contract" "target=${TARGET_KIND}\nimage_sha256=${sha}\nexpanded_fields=35\nimports=none\narithmetic=separate_f32\nsource_authority=none\n")
