cmake_minimum_required(VERSION 3.20)
if(NOT ISA MATCHES "^(avx|avx2|avx512f)$")
  message(FATAL_ERROR "Unknown closed ISA object")
endif()
file(READ "${IR}.manifest" manifest)
file(SHA256 "${IR}" digest)
if(NOT manifest MATCHES "\nisa=${ISA}\n" OR NOT manifest MATCHES "\nllvm_sha256=${digest}\n" OR
   NOT manifest MATCHES "\narithmetic_fma_permission=none\n")
  message(FATAL_ERROR "ISA object lacks matching compiler-issued provenance")
endif()
execute_process(COMMAND "${NM}" --defined-only --extern-only "${OBJECT}"
  RESULT_VARIABLE status OUTPUT_VARIABLE definitions ERROR_VARIABLE error)
set(symbol "__matcore_strict_gemm_f32_${ISA}_v1")
if(NOT status EQUAL 0 OR NOT definitions MATCHES " T ${symbol}\n" OR
   NOT definitions MATCHES " T _mlir_ciface_${symbol}\n")
  message(FATAL_ERROR "Distinct ISA object symbols missing: ${definitions} ${error}")
endif()
string(REGEX REPLACE "[^\n]* T (_mlir_ciface_)?${symbol}\n?" "" other "${definitions}")
if(SANITIZED)
  string(REGEX REPLACE "[^\n]* C ___asan_globals_registered\n?" "" other "${other}")
endif()
string(STRIP "${other}" other)
if(NOT other STREQUAL "")
  message(FATAL_ERROR "Unknown ISA object exported definition: ${other}")
endif()
execute_process(COMMAND "${NM}" --undefined-only "${OBJECT}"
  RESULT_VARIABLE status OUTPUT_VARIABLE imports ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Cannot inspect ISA object: ${error}")
endif()
string(REGEX REPLACE "[^\n]*[ \t]memset\n?" "" imports "${imports}")
if(SANITIZED)
  string(REGEX REPLACE "[^\n]*(__asan_|__start_asan_|__stop_asan_)[^\n]*\n?" "" imports "${imports}")
endif()
string(STRIP "${imports}" imports)
if(NOT imports STREQUAL "")
  message(FATAL_ERROR "Unknown allocation/provider/fused import: ${imports}")
endif()
execute_process(COMMAND "${OBJDUMP}" -d --no-show-raw-insn "${OBJECT}"
  RESULT_VARIABLE status OUTPUT_VARIABLE assembly ERROR_VARIABLE error)
if(NOT status EQUAL 0 OR NOT assembly MATCHES "file format elf64-x86-64" OR
   assembly MATCHES "vfm|vfnm|vcvtph|vcvtps2ph|tmm[0-9]|%k[0-9]")
  message(FATAL_ERROR "Invalid strict ISA machine/arithmetic footprint: ${error}")
endif()
# Deliberately closed vector mnemonic vocabulary. This recipe claims f32
# mul/add, broadcast and movement, not all AVX subextensions or arithmetic.
string(REGEX MATCHALL "[\n][ \t]*[0-9a-f]+:[ \t]+v[a-z0-9]+" vector_lines "${assembly}")
foreach(line IN LISTS vector_lines)
  string(REGEX REPLACE ".*:[ \t]+" "" mnemonic "${line}")
  if(NOT mnemonic MATCHES "^(vaddps|vaddss|vmulps|vmulss|vmovss|vmovups|vmovaps|vxorps|vzeroupper|vinsertf128|vshufps|vbroadcastss)$")
    message(FATAL_ERROR "Unknown strict vector opcode: ${mnemonic}")
  endif()
endforeach()
if(NOT ISA STREQUAL "avx512f" AND assembly MATCHES "%zmm[0-9]|%[xyz]mm(1[6-9]|2[0-9]|3[01])")
  message(FATAL_ERROR "AVX512 register escaped a narrower ISA object")
endif()
if(ISA STREQUAL "avx" AND assembly MATCHES "vbroadcastss[ \t]+%")
  message(FATAL_ERROR "AVX2 register broadcast escaped AVX-only object")
endif()
if(NOT SANITIZED)
  set(width ymm)
  if(ISA STREQUAL "avx512f")
    set(width zmm)
  endif()
  if(NOT assembly MATCHES "vmulps[^\n]*%${width}" OR NOT assembly MATCHES "vaddps[^\n]*%${width}" OR
     NOT assembly MATCHES "vmulss" OR NOT assembly MATCHES "vaddss")
    message(FATAL_ERROR "Requested ISA did not produce actual ${width} mul/add and scalar tails")
  endif()
  if(ISA STREQUAL "avx2" AND NOT assembly MATCHES "vbroadcastss[ \t]+%xmm[0-9]+, %ymm")
    message(FATAL_ERROR "AVX2-exclusive register broadcast not established")
  endif()
endif()
message(STATUS "Strict ${ISA} object: distinct symbols, bounded imports, separate arithmetic; sanitized=${SANITIZED}")
