#!/usr/bin/env python3
"""Focused native LibTooling and bootstrap parity checks."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path


def command(
    extractor: Path, source: Path, output: Path, frontend: str | None = None
) -> list[str]:
    result = [str(extractor)]
    if frontend is not None:
        result.append(f"--frontend={frontend}")
    result.extend(
        [
            "--input",
            source.as_posix(),
            "--ir-out",
            str(output),
            "--",
            "clang++",
            "-std=c++20",
            "-Icompiler/include",
            "-Icompiler/tests/frontend",
            source.as_posix(),
        ]
    )
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--extractor", type=Path, required=True)
    arguments = parser.parse_args()
    extractor = arguments.extractor.resolve()
    repository = Path(__file__).resolve().parents[3]
    fixtures = Path("compiler/tests/frontend")
    failures: list[str] = []

    with tempfile.TemporaryDirectory(prefix="matcore-native-focused-") as temporary:
        output_root = Path(temporary)
        source = fixtures / "gemm_capture.mdsl"
        native_path = output_root / "native.json"
        native = subprocess.run(
            command(extractor, source, native_path),
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if native.returncode != 0:
            failures.append(f"default native extraction failed:\n{native.stderr}")
        else:
            document = json.loads(native_path.read_text())
            if document.get("producer") != "clang-libtooling-v1":
                failures.append("default extraction did not use native producer")
            if len(document.get("operations", [])) != 1:
                failures.append("native extraction did not capture one GEMM")

        explicit_path = output_root / "explicit-native.json"
        explicit = subprocess.run(
            command(extractor, source, explicit_path, "native"),
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if explicit.returncode != 0 or (
            native_path.exists()
            and explicit_path.exists()
            and explicit_path.read_bytes() != native_path.read_bytes()
        ):
            failures.append("explicit and default native modes differ")

        bootstrap_path = output_root / "bootstrap.json"
        bootstrap = subprocess.run(
            command(extractor, source, bootstrap_path, "ast-json-bootstrap"),
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if bootstrap.returncode != 0:
            failures.append(f"explicit bootstrap extraction failed:\n{bootstrap.stderr}")
        elif native_path.exists():
            native_document = json.loads(native_path.read_text())
            bootstrap_document = json.loads(bootstrap_path.read_text())
            if bootstrap_document.get("producer") != "clang-ast-json-bootstrap-v0":
                failures.append("bootstrap producer is not explicitly labeled")
            native_document.pop("producer", None)
            bootstrap_document.pop("producer", None)
            if native_document != bootstrap_document:
                failures.append("native/bootstrap semantic IR parity failed")

        negative_cases = {
            "unqualified": "must be directly qualified",
            "indirect": "indirect or function-pointer",
            "template_call": "inside templates",
            "lambda_call": "inside lambdas",
            "macro_call": "generated by macros",
            "header_origin": "written directly in the input .mdsl file",
            "untrusted_header": "trusted <matcore/mdsl.h>",
        }
        for name, expected in negative_cases.items():
            output = output_root / f"{name}.json"
            completed = subprocess.run(
                command(extractor, fixtures / f"{name}.mdsl", output),
                cwd=repository,
                text=True,
                capture_output=True,
                check=False,
            )
            if completed.returncode == 0:
                failures.append(f"native negative {name} unexpectedly succeeded")
            elif expected not in completed.stderr:
                failures.append(
                    f"native negative {name} lacked {expected!r}:\n{completed.stderr}"
                )
            if output.exists():
                failures.append(f"native negative {name} emitted an IR artifact")

        wrong_compiler = subprocess.run(
            [
                str(extractor),
                "--frontend=native",
                "--clang",
                "/usr/bin/clang++-22",
                "--input",
                source.as_posix(),
                "--ir-out",
                str(output_root / "wrong-compiler.json"),
                "--",
                "-std=c++20",
                source.as_posix(),
            ],
            cwd=repository,
            text=True,
            capture_output=True,
            check=False,
        )
        if wrong_compiler.returncode == 0 or "cannot honor a different" not in wrong_compiler.stderr:
            failures.append("native mode did not reject a mismatched --clang executable")

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}", file=sys.stderr)
        return 1
    print("native frontend focused tests: 15 checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
