cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/experimental_regions_consumer_link.cmake")

if(DEFINED NEGATIVE_PROVIDER)
  matcore_installed_provider_link_flags(ON "${NEGATIVE_PROVIDER}" flags provider)
  message(FATAL_ERROR "Invalid provider unexpectedly passed the file guard")
endif()
if(DEFINED ROUNDTRIP_FLAGS)
  separate_arguments(roundtrip NATIVE_COMMAND "${ROUNDTRIP_FLAGS}")
  if(NOT "${roundtrip}" STREQUAL "${EXPECTED_FLAGS}")
    message(FATAL_ERROR "ABI-child link flags changed after native-command parsing")
  endif()
  message(STATUS "ABI-child argument roundtrip preserved every token")
  return()
endif()

if(NOT DEFINED SCRATCH)
  message(FATAL_ERROR "Supply an existing empty scratch directory via -DSCRATCH")
endif()
if(NOT IS_ABSOLUTE "${SCRATCH}" OR NOT IS_DIRECTORY "${SCRATCH}")
  message(FATAL_ERROR "SCRATCH must be an existing absolute directory")
endif()
file(GLOB existing "${SCRATCH}/*")
if(existing)
  message(FATAL_ERROR "SCRATCH must be empty; existing files are never overwritten")
endif()
set(provider_directory "${SCRATCH}/provider path,with-comma")
set(blob_directory "${SCRATCH}/blob store,elsewhere")
file(MAKE_DIRECTORY "${provider_directory}" "${blob_directory}")
set(provider_file "${provider_directory}/libconfigured-provider.so")
set(provider_blob "${blob_directory}/versioned.bin")
file(WRITE "${provider_blob}" "file-identity fixture only; not a provider implementation\n")
file(CREATE_LINK "${provider_blob}" "${provider_file}" SYMBOLIC)
file(CREATE_LINK "${provider_blob}" "${provider_directory}/libconfigured-provider.so.0" SYMBOLIC)
if(NOT EXISTS "${provider_directory}/libconfigured-provider.so.0" OR
    EXISTS "${blob_directory}/libconfigured-provider.so.0")
  message(FATAL_ERROR "Cross-directory fixture must keep the SONAME alias only in the configured directory")
endif()
file(REAL_PATH "${provider_file}" physical_provider)
if(NOT physical_provider STREQUAL provider_blob OR physical_provider STREQUAL provider_file)
  message(FATAL_ERROR "Provider fixture did not establish a distinct cross-directory physical target")
endif()
matcore_installed_provider_link_flags(ON "${provider_file}" flags provider)
set(expected -Xlinker --push-state -Xlinker --no-as-needed
  "${provider_file}" -Xlinker --pop-state -Xlinker -rpath -Xlinker "${provider_directory}")
if(NOT "${flags}" STREQUAL "${expected}" OR NOT provider STREQUAL provider_file)
  message(FATAL_ERROR "Provider-ON did not preserve the configured symlink file and its SONAME directory")
endif()
foreach(argument IN LISTS flags)
  if(argument STREQUAL "-lopenblas" OR argument MATCHES "^-Wl,")
    message(FATAL_ERROR "Provider link flags introduced name lookup or comma-split linker payload")
  endif()
endforeach()
set(runtime_directory "${SCRATCH}/runtime path,with-comma")
set(all_flags "-L${runtime_directory}" -lmatcore_runtime ${flags} -lm -pthread
  -Xlinker -rpath -Xlinker "${runtime_directory}" -fsanitize=address,undefined
  "${SCRATCH}/path with \"quote\",comma and \\backslash")
matcore_serialize_installed_link_flags(serialized ${all_flags})
separate_arguments(roundtrip NATIVE_COMMAND "${serialized}")
if(NOT "${roundtrip}" STREQUAL "${all_flags}")
  message(FATAL_ERROR "Local native-command serialization changed link argument identity")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DROUNDTRIP_FLAGS=${serialized}"
  "-DEXPECTED_FLAGS=${all_flags}" -P "${CMAKE_CURRENT_LIST_FILE}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "ABI-child argument roundtrip failed: ${output}\n${error}")
endif()
message(STATUS "${output}")

# Reuse the same outputs deliberately: OFF must not inherit the previous ON
# configuration, even when a stale or now-invalid provider path is supplied.
matcore_installed_provider_link_flags(OFF "${SCRATCH}/missing-stale-provider.so" flags provider)
if(NOT flags STREQUAL "" OR NOT provider STREQUAL "")
  message(FATAL_ERROR "Provider-OFF retained stale provider arguments or identity")
endif()
foreach(invalid IN ITEMS "" "${SCRATCH}/missing.so" "${provider_directory}" "relative-provider.so")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DNEGATIVE_PROVIDER=${invalid}"
    -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(status EQUAL 0 OR NOT error MATCHES "MDSLC_INSTALL_PROVIDER_FILE")
    message(FATAL_ERROR "Invalid provider guard failed for '${invalid}': ${output}\n${error}")
  endif()
endforeach()
message(STATUS "Provider ON/OFF freshness, cross-directory configured spelling, four invalid inputs, and ABI serialization passed")
