cmake_minimum_required(VERSION 3.24)
foreach(required IN ITEMS BINARY_DIR COMPILER_SOURCE INSTALL_BINDIR)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Missing installed program test input ${required}")
  endif()
endforeach()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(work "${BINARY_DIR}/installed-program-${nonce}")
set(prefix "${work}/prefix")
set(source "${work}/source")
set(run "${work}/run")
file(MAKE_DIRECTORY "${source}" "${run}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BINARY_DIR}" --prefix "${prefix}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status STREQUAL "0")
  message(FATAL_ERROR "Installed program package creation failed: ${status}\n${output}\n${error}")
endif()
set(fixtures api.h first.mdsl second.mdsl main.cpp main_body.h value_helper.h)
foreach(name IN LISTS fixtures)
  file(COPY "${COMPILER_SOURCE}/tests/program/fixtures/${name}" DESTINATION "${source}")
  file(SHA256 "${source}/${name}" "source_hash_${name}")
endforeach()
set(driver "${prefix}/${INSTALL_BINDIR}/mdslc-region")
file(SHA256 "${driver}" driver_before)
set(executable "${run}/program")
execute_process(COMMAND "${driver}" --program --host "${source}/main.cpp"
  --region "${source}/first.mdsl" first --region "${source}/second.mdsl" second
  --candidate generated-strict -o "${executable}"
  WORKING_DIRECTORY "${run}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status STREQUAL "0" OR NOT error STREQUAL "" OR NOT EXISTS "${executable}" OR
   NOT output STREQUAL "VALIDATED program ownership and ABI before cross-TU link/optimization\nCROSS_TU_LINK 1\nCROSS_TU_LINK 2\nPUBLISHED authenticated multi-source program\n")
  message(FATAL_ERROR "Installed source-program compilation failed: ${status}\n${output}\n${error}")
endif()
file(SHA256 "${executable}" executable_before)
execute_process(COMMAND "${executable}" WORKING_DIRECTORY "${run}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status STREQUAL "0" OR NOT error STREQUAL "" OR
   NOT output STREQUAL "PASS authenticated_multi_tu 37 checks\n")
  message(FATAL_ERROR "Installed multi-source execution failed: ${status}\n${output}\n${error}")
endif()
file(SHA256 "${driver}" driver_after)
file(SHA256 "${executable}" executable_after)
if(NOT driver_before STREQUAL driver_after OR NOT executable_before STREQUAL executable_after)
  message(FATAL_ERROR "Installed driver or executable changed during execution")
endif()
foreach(name IN LISTS fixtures)
  file(SHA256 "${source}/${name}" actual)
  if(NOT actual STREQUAL "${source_hash_${name}}")
    message(FATAL_ERROR "Installed program source changed: ${name}")
  endif()
endforeach()
message(STATUS "Installed program PASS37: driver=${driver_after}; executable=${executable_after}")
