execute_process(COMMAND "${NM}" --defined-only --extern-only "${ARCHIVE}"
  RESULT_VARIABLE status OUTPUT_VARIABLE symbols ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "cannot inspect candidate archive: ${error}")
endif()
if(symbols MATCHES "configureForTesting|allocationAttemptsForTesting")
  message(FATAL_ERROR "production registry exported test authority")
endif()
if(NOT symbols MATCHES "_mlir_ciface___matcore_strict_gemm_f32_v1")
  message(FATAL_ERROR "generated candidate not linked into production registry")
endif()
if(CPU_X86 AND NOT symbols MATCHES "_mlir_ciface___matcore_reassociate_gemm_f32_avx2_v1")
  message(FATAL_ERROR "generated reassociate candidate not linked into production registry")
endif()
if(NOT CPU_X86 AND symbols MATCHES "_mlir_ciface___matcore_reassociate_gemm_f32_avx2_v1")
  message(FATAL_ERROR "x86-only reassociate symbol leaked into ARM production registry")
endif()
