#include "MatcoreGemmOutputPattern.h"
#include "MatcoreCpuGemmCandidate.h"

#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/TransformOps/DialectExtension.h"
#include "mlir/Dialect/Linalg/Transforms/TilingInterfaceImpl.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Transforms/Passes.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/IR/TransformOps.h"
#include "mlir/Dialect/Transform/Transforms/TransformInterpreterUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/PassManager.h"
#include "llvm/ADT/STLExtras.h"

namespace matcore::mdslc::gemm_pattern {
namespace {
using namespace mlir;

bool reject(std::string &error, llvm::StringRef message) {
  error = "strict GEMM output pattern: " + message.str();
  return false;
}

bool indexIs(Value value, std::int64_t expected) {
  auto constant = value.getDefiningOp<arith::ConstantIndexOp>();
  if (constant) return constant.value() == expected;
  auto dim = value.getDefiningOp<memref::DimOp>();
  auto subview = dim ? dim.getSource().getDefiningOp<memref::SubViewOp>()
                     : memref::SubViewOp{};
  auto dimension = dim ? dim.getIndex().getDefiningOp<arith::ConstantIndexOp>()
                       : arith::ConstantIndexOp{};
  if (!subview || !dimension || dimension.value() < 0 ||
      static_cast<std::size_t>(dimension.value()) >= subview.getMixedSizes().size())
    return false;
  auto size = subview.getMixedSizes()[dimension.value()];
  if (auto fixed = getConstantIntValue(size)) return *fixed == expected;
  auto dynamic = dyn_cast<Value>(size);
  return dynamic && indexIs(dynamic, expected);
}

Value resolveExtent(Value value) {
  auto dim = value.getDefiningOp<memref::DimOp>();
  auto subview = dim ? dim.getSource().getDefiningOp<memref::SubViewOp>()
                     : memref::SubViewOp{};
  auto dimension = dim ? dim.getIndex().getDefiningOp<arith::ConstantIndexOp>()
                       : arith::ConstantIndexOp{};
  if (!subview || !dimension || dimension.value() < 0 ||
      static_cast<std::size_t>(dimension.value()) >= subview.getMixedSizes().size())
    return value;
  auto dynamic = dyn_cast<Value>(subview.getMixedSizes()[dimension.value()]);
  return dynamic ? resolveExtent(dynamic) : value;
}

bool dimensionIs(Value value, Value matrix, std::int64_t dimension) {
  value = resolveExtent(value);
  auto dim = value.getDefiningOp<memref::DimOp>();
  return dim && dim.getSource() == matrix &&
         indexIs(dim.getIndex(), dimension);
}

bool matrix(Type type) {
  auto memref = dyn_cast<MemRefType>(type);
  return memref && memref.getRank() == 2 && memref.isDynamicDim(0) &&
         memref.isDynamicDim(1) && memref.getElementType().isF32() &&
         memref.getLayout().isIdentity() && !memref.getMemorySpace();
}

// Only integer index glue generated by the pinned tiler/alias folder is
// interpreted here. The complete module is additionally compared with replay.
AffineExpr indexExpression(Value value, Value first, Value second,
                           unsigned depth = 0) {
  auto *context = value.getContext();
  if (value == first) return getAffineDimExpr(0, context);
  if (value == second) return getAffineDimExpr(1, context);
  if (depth == 8) return {};
  if (auto constant = value.getDefiningOp<arith::ConstantIndexOp>())
    return getAffineConstantExpr(constant.value(), context);
  if (auto add = value.getDefiningOp<arith::AddIOp>()) {
    auto lhs = indexExpression(add.getLhs(), first, second, depth + 1);
    auto rhs = indexExpression(add.getRhs(), first, second, depth + 1);
    return lhs && rhs ? simplifyAffineExpr(lhs + rhs, 2, 0) : AffineExpr{};
  }
  auto apply = value.getDefiningOp<affine::AffineApplyOp>();
  if (!apply || apply.getAffineMap().getNumResults() != 1) return {};
  SmallVector<AffineExpr> dims, symbols;
  for (auto [index, operand] : llvm::enumerate(apply.getOperands())) {
    auto expression = indexExpression(operand, first, second, depth + 1);
    if (!expression) return {};
    (index < apply.getAffineMap().getNumDims() ? dims : symbols)
        .push_back(expression);
  }
  return simplifyAffineExpr(apply.getAffineMap().getResult(0)
                                .replaceDimsAndSymbols(dims, symbols),
                            2, 0);
}

bool sumIndex(Value value, Value first, Value second) {
  auto expression = indexExpression(value, first, second);
  return expression && expression ==
      getAffineDimExpr(0, value.getContext()) +
          getAffineDimExpr(1, value.getContext());
}

bool sameIndex(Value first, Value second) {
  if (first == second) return true;
  auto lhs = first.getDefiningOp<affine::AffineApplyOp>();
  auto rhs = second.getDefiningOp<affine::AffineApplyOp>();
  return lhs && rhs && lhs.getAffineMap() == rhs.getAffineMap() &&
         lhs.getOperands() == rhs.getOperands();
}

bool sameIndices(ValueRange first, ValueRange second) {
  return first.size() == 2 && second.size() == 2 &&
         sameIndex(first[0], second[0]) && sameIndex(first[1], second[1]);
}

bool tailBound(Value value, Value origin, Value extent, std::int64_t tile) {
  // A unit tile cannot have a shorter positive tail inside its bounded loop.
  if (tile == 1 && indexIs(value, 1)) return true;
  value = resolveExtent(value);
  auto minimum = value.getDefiningOp<affine::AffineMinOp>();
  if (!minimum || minimum.getAffineMap().getNumResults() != 2) return false;
  SmallVector<AffineExpr> dims, symbols;
  for (auto [index, operand] : llvm::enumerate(minimum.getOperands())) {
    auto expression = indexExpression(operand, origin, extent);
    if (!expression) return false;
    (index < minimum.getAffineMap().getNumDims() ? dims : symbols)
        .push_back(expression);
  }
  auto expectedRemaining = simplifyAffineExpr(
      getAffineDimExpr(1, value.getContext()) -
          getAffineDimExpr(0, value.getContext()),
      2, 0);
  auto expectedTile = getAffineConstantExpr(tile, value.getContext());
  bool remaining = false, constant = false;
  for (auto expression : minimum.getAffineMap().getResults()) {
    expression = simplifyAffineExpr(
        expression.replaceDimsAndSymbols(dims, symbols), 2, 0);
    remaining |= expression == expectedRemaining;
    constant |= expression == expectedTile;
  }
  return remaining && constant;
}

// This is a semantic envelope of actual scalar loops, not another tiler.
// Upstream supplies all loops and indices. The independent checks defend full
// output coverage, tail ownership, increasing unpartitioned K, operand order,
// complete initial overwrite and exact C accumulator/destination dataflow.
bool scalarEnvelope(ModuleOp scheduled, const OutputTilePatternV1 &tiles,
                    std::string &error) {
  if (!scheduled || failed(verify(scheduled)) ||
      !scheduled->getAttrs().empty() ||
      !llvm::hasSingleElement(scheduled.getBody()->getOperations()))
    return reject(error, "scheduled module ownership changed");
  bool attributes = false;
  scheduled.walk([&](Operation *op) {
    attributes |= !op->getDiscardableAttrDictionary().empty();
  });
  if (attributes) return reject(error, "unsupported semantic/authority attribute");
  auto original = dyn_cast<func::FuncOp>(scheduled.getBody()->front());
  if (!original || original.getName() != cpu_candidate::kStrictGemmSymbolV1 ||
      original.getNumArguments() != 3 || original.getNumResults() != 1 ||
      original->getAttrs().size() != 2 ||
      !llvm::hasSingleElement(original.getBody()) ||
      original.getResultTypes()[0] != original.getArgument(2).getType())
    return reject(error, "scheduled function identity/type changed");
  for (auto type : original.getArgumentTypes())
    if (!matrix(type)) return reject(error, "scheduled matrix layout changed");

  OwningOpRef<ModuleOp> lowered = scheduled.clone();
  PassManager loops(scheduled.getContext());
  loops.addNestedPass<func::FuncOp>(createConvertLinalgToLoopsPass());
  loops.addPass(memref::createFoldMemRefAliasOpsPass());
  // Do not canonicalize away a unit local M/N loop before checking its order
  // and ownership. The production lowering may fold these proven unit loops.
  if (failed(loops.run(*lowered)) || failed(verify(*lowered)))
    return reject(error, "independent scalar-loop inspection failed");
  auto function = *lowered->getOps<func::FuncOp>().begin();
  const auto a = function.getArgument(0), b = function.getArgument(1),
             c = function.getArgument(2);
  unsigned multiplies = 0, adds = 0, loads = 0, stores = 0, loopCount = 0;
  bool invalid = false;
  scf::ForOp reduction, zeroFill;
  arith::MulFOp productOp;
  lowered->walk([&](Operation *op) {
    if (!isa<ModuleOp, func::FuncOp, func::ReturnOp, arith::ConstantOp,
             arith::AddIOp, arith::MulIOp, arith::MulFOp, arith::AddFOp,
             memref::DimOp, memref::SubViewOp, memref::LoadOp, memref::StoreOp,
             affine::AffineApplyOp, affine::AffineMinOp, scf::ForOp,
             scf::YieldOp>(op)) invalid = true;
    if (auto loop = dyn_cast<scf::ForOp>(op)) {
      ++loopCount;
      invalid |= loop.getNumResults() || !loop.getInitArgs().empty();
    }
    if (auto mul = dyn_cast<arith::MulFOp>(op)) {
      ++multiplies;
      productOp = mul;
      auto lhs = mul.getLhs().getDefiningOp<memref::LoadOp>();
      auto rhs = mul.getRhs().getDefiningOp<memref::LoadOp>();
      invalid |= !mul.getType().isF32() ||
                 mul.getFastmath() != arith::FastMathFlags::none ||
                 !lhs || !rhs || lhs.getMemRef() != a || rhs.getMemRef() != b;
      if (!lhs || !rhs || lhs.getIndices().size() != 2 ||
          rhs.getIndices().size() != 2) { invalid = true; return; }
      auto k = dyn_cast<BlockArgument>(lhs.getIndices()[1]);
      auto loop = k ? dyn_cast<scf::ForOp>(k.getOwner()->getParentOp())
                    : scf::ForOp{};
      invalid |= !loop || lhs.getIndices()[1] != rhs.getIndices()[0] ||
                 (loop && (loop.getInductionVar() != k ||
                    !indexIs(loop.getLowerBound(), 0) ||
                    !indexIs(loop.getStep(), 1) ||
                    !dimensionIs(loop.getUpperBound(), a, 1)));
      reduction = loop;
    }
    if (auto add = dyn_cast<arith::AddFOp>(op)) {
      ++adds;
      auto old = add.getLhs().getDefiningOp<memref::LoadOp>();
      auto product = add.getRhs().getDefiningOp<arith::MulFOp>();
      invalid |= !add.getType().isF32() ||
                 add.getFastmath() != arith::FastMathFlags::none ||
                 !old || old.getMemRef() != c || !product;
    }
    if (auto load = dyn_cast<memref::LoadOp>(op)) {
      ++loads;
      invalid |= load.getMemRef() != a && load.getMemRef() != b &&
                 load.getMemRef() != c;
    }
    if (auto store = dyn_cast<memref::StoreOp>(op)) {
      ++stores;
      invalid |= store.getMemRef() != c;
      if (auto add = store.getValue().getDefiningOp<arith::AddFOp>()) {
        auto old = add.getLhs().getDefiningOp<memref::LoadOp>();
        auto product = add.getRhs().getDefiningOp<arith::MulFOp>();
        auto lhs = product ? product.getLhs().getDefiningOp<memref::LoadOp>()
                           : memref::LoadOp{};
        auto rhs = product ? product.getRhs().getDefiningOp<memref::LoadOp>()
                           : memref::LoadOp{};
        invalid |= !old || !lhs || !rhs ||
                   !sameIndices(store.getIndices(), old.getIndices());
        if (lhs && rhs && store.getIndices().size() == 2)
          invalid |= !sameIndex(store.getIndices()[0], lhs.getIndices()[0]) ||
                     !sameIndex(store.getIndices()[1], rhs.getIndices()[1]);
      } else {
        auto constant = store.getValue().getDefiningOp<arith::ConstantOp>();
        auto zero = constant ? dyn_cast<FloatAttr>(constant.getValue()) : FloatAttr{};
        auto n = store->getParentOfType<scf::ForOp>();
        auto m = n ? n->getParentOfType<scf::ForOp>() : scf::ForOp{};
        invalid |= !zero || !zero.getValue().isZero() ||
                   zero.getValue().isNegative() || !n || !m;
        if (n && m) {
          invalid |= bool(zeroFill) || m->getBlock() != &function.front() ||
              !indexIs(m.getLowerBound(), 0) || !indexIs(n.getLowerBound(), 0) ||
              !indexIs(m.getStep(), 1) || !indexIs(n.getStep(), 1) ||
              !dimensionIs(m.getUpperBound(), c, 0) ||
              !dimensionIs(n.getUpperBound(), c, 1) ||
              !sameIndices(store.getIndices(), {m.getInductionVar(), n.getInductionVar()});
          zeroFill = m;
        }
      }
    }
  });
  if (invalid || multiplies != 1 || adds != 1 || loads != 3 || stores != 2 ||
      loopCount != 7 || !reduction || !zeroFill)
    return reject(error, "scalar memory/arithmetic/increasing-K envelope changed");

  auto localM = reduction->getParentOfType<scf::ForOp>();
  auto tileN = localM ? localM->getParentOfType<scf::ForOp>() : scf::ForOp{};
  auto tileM = tileN ? tileN->getParentOfType<scf::ForOp>() : scf::ForOp{};
  auto localN = productOp->getParentOfType<scf::ForOp>();
  if (!localM || !tileN || !tileM || !localN ||
      localN->getParentOp() != reduction.getOperation() ||
      tileM->getBlock() != &function.front())
    return reject(error, "scalar loop nest lost tile-M/tile-N/local-M/K/local-N order");
  if (!indexIs(tileM.getLowerBound(), 0) ||
      !indexIs(tileN.getLowerBound(), 0) ||
      !indexIs(tileM.getStep(), tiles.tile_m) ||
      !indexIs(tileN.getStep(), tiles.tile_n) ||
      !dimensionIs(tileM.getUpperBound(), a, 0) ||
      !dimensionIs(tileN.getUpperBound(), b, 1))
    return reject(error, "M/N tile origins, parameter steps or complete bounds changed");
  if (!indexIs(localM.getLowerBound(), 0) ||
      !indexIs(localN.getLowerBound(), 0) ||
      !indexIs(localM.getStep(), 1) || !indexIs(localN.getStep(), 1))
    return reject(error, "local M/N scalar origin or unit steps changed");
  if (!tailBound(localM.getUpperBound(), tileM.getInductionVar(),
                 tileM.getUpperBound(), tiles.tile_m))
    return reject(error, "M local loop lost bounded tile tail");
  if (!tailBound(localN.getUpperBound(), tileN.getInductionVar(),
                 tileN.getUpperBound(), tiles.tile_n))
    return reject(error, "N local loop lost bounded tile tail");
  auto lhs = productOp.getLhs().getDefiningOp<memref::LoadOp>();
  auto rhs = productOp.getRhs().getDefiningOp<memref::LoadOp>();
  if (!lhs || !rhs ||
      !sumIndex(lhs.getIndices()[0], tileM.getInductionVar(),
                localM.getInductionVar()) ||
      !sumIndex(rhs.getIndices()[1], tileN.getInductionVar(),
                localN.getInductionVar()) ||
      !zeroFill->isBeforeInBlock(tileM))
    return reject(error, "tile indices lost disjoint original-C ownership or dominating fill");
  auto returned = dyn_cast<func::ReturnOp>(function.front().back());
  if (!returned || returned.getNumOperands() != 1 || returned.getOperand(0) != c)
    return reject(error, "scheduled return lost original destination identity");
  return true;
}

OwningOpRef<ModuleOp> runSchedule(ModuleOp bufferized,
                                const OutputTilePatternV1 &tiles,
                                std::string &error) {
  auto transformText = strictGemmOutputTileTransformV1(tiles, error);
  if (transformText.empty()) return {};
  auto *context = bufferized.getContext();
  DialectRegistry registry;
  registry.insert<affine::AffineDialect, scf::SCFDialect>();
  linalg::registerTransformDialectExtension(registry);
  linalg::registerTilingInterfaceExternalModels(registry);
  context->appendDialectRegistry(registry);
  context->getOrLoadDialect<affine::AffineDialect>();
  context->getOrLoadDialect<scf::SCFDialect>();
  context->getOrLoadDialect<transform::TransformDialect>();
  auto transform = parseSourceString<ModuleOp>(transformText, ParserConfig(context));
  if (!transform) { reject(error, "cannot parse instantiated upstream Transform"); return {}; }
  auto entry = transform->lookupSymbol<transform::NamedSequenceOp>(
      transform::TransformDialect::kTransformEntryPointSymbolName);
  // Failed upstream transformations may partially mutate their input. No
  // verified original stage or failed payload is ever reused as a candidate.
  OwningOpRef<ModuleOp> scheduled = bufferized.clone();
  if (!entry || failed(transform::applyTransformNamedSequence(
          scheduled->getOperation(), entry.getOperation(), *transform,
          transform::TransformOptions().enableExpensiveChecks(true))) ||
      failed(verify(*scheduled))) {
    reject(error, "parameterized upstream Transform derivation failed");
    return {};
  }
  return scheduled;
}
} // namespace

bool validateOutputTilePatternV1(const OutputTilePatternV1 &tiles,
                                 std::string &error) {
  error.clear();
  if (tiles.tile_m < 1 || tiles.tile_m > 64 ||
      tiles.tile_n < 1 || tiles.tile_n > 64)
    return reject(error, "M/N tile parameters must both be integers in 1..64");
  return true;
}

std::string strictGemmOutputTileTransformV1(const OutputTilePatternV1 &tiles,
                                           std::string &error) {
  if (!validateOutputTilePatternV1(tiles, error)) return {};
  return "module attributes {transform.with_named_sequence} {\n"
      "  transform.named_sequence @__transform_main(%root: !transform.any_op {transform.readonly}) {\n"
      "    %matmul = transform.structured.match ops{[\"linalg.matmul\"]} in %root : (!transform.any_op) -> !transform.any_op\n"
      "    %tiled, %m, %n = transform.structured.tile_using_for %matmul tile_sizes [" +
      std::to_string(tiles.tile_m) + ", " + std::to_string(tiles.tile_n) +
      ", 0] : (!transform.any_op) -> (!transform.any_op, !transform.op<\"scf.for\">, !transform.op<\"scf.for\">)\n"
      "    %generic = transform.structured.generalize %tiled : (!transform.any_op) -> !transform.any_op\n"
      "    %scheduled = transform.structured.interchange %generic iterator_interchange = [0, 2, 1] : (!transform.any_op) -> !transform.any_op\n"
      "    transform.yield\n  }\n}\n";
}

OwningOpRef<ModuleOp> deriveStrictGemmOutputTiledV1(
    ModuleOp canonical_bufferized, const OutputTilePatternV1 &tiles,
    std::string &error) {
  if (!validateOutputTilePatternV1(tiles, error) ||
      !cpu_candidate::verifyStrictGemmBufferizedV1(canonical_bufferized, error))
    return {};
  auto result = runSchedule(canonical_bufferized, tiles, error);
  if (!result || !verifyStrictGemmOutputTiledV1(*result, tiles, error)) return {};
  return result;
}

bool verifyStrictGemmOutputTiledV1(ModuleOp scheduled,
                                  const OutputTilePatternV1 &tiles,
                                  std::string &error) {
  if (!validateOutputTilePatternV1(tiles, error) ||
      !scalarEnvelope(scheduled, tiles, error)) return false;
  auto original = cpu_candidate::buildStrictGemmStagesV1(*scheduled.getContext());
  if (!original) { error = original.error; return false; }
  auto expected = runSchedule(*original.bufferized, tiles, error);
  if (!expected) return false;
  if (!OperationEquivalence::isEquivalentTo(scheduled, *expected,
                                           OperationEquivalence::IgnoreLocations))
    return reject(error, "scheduled payload differs from parameter-bound upstream replay");
  return true;
}

} // namespace matcore::mdslc::gemm_pattern
