#loc1 = loc("compiler/tests/frontend/gemm_capture.mdsl":21:3)
module attributes {mdsl.bridge_schema = "matcore-mlir-semantic-v1", mdsl.capture_schema = "matcore-ir-v1", mdsl.capture_version = 1 : i32, mdsl.composition_schema = "matcore-mlir-composition-v1", mdsl.composition_version = 1 : i32, mdsl.execution_intent = "generic", mdsl.numerical_profile = "explicit-gemm-f32-v1", mdsl.producer = "clang-libtooling-v1", mdsl.semantic_version = 1 : i32, mdsl.source_file = "compiler/tests/frontend/gemm_capture.mdsl", mdsl.translation_unit = "compiler/tests/frontend/gemm_capture.mdsl"} {
  func.func @__matcore_semantic_mc_3c5b6d5e7992fb7b249de44210c6415d(%arg0: tensor<?x?xf32> loc("compiler/tests/frontend/gemm_capture.mdsl":21:3), %arg1: tensor<?x?xf32> loc("compiler/tests/frontend/gemm_capture.mdsl":21:3), %arg2: tensor<?x?xf32> loc("compiler/tests/frontend/gemm_capture.mdsl":21:3)) -> tensor<?x?xf32> attributes {mdsl.capture_ordinal = 0 : i64, mdsl.site_id = "mc_3c5b6d5e7992fb7b249de44210c6415d"} {
    %0 = mdsl.gemm %arg0, %arg1 outs(%arg2 : tensor<?x?xf32>) {accumulation_type = f32, aliasing = [{contract = "required_precondition", first = "output", relation = "no_alias", second = "lhs"}, {contract = "required_precondition", first = "output", relation = "no_alias", second = "rhs"}], effects = {read_write = [], reads = ["lhs", "rhs"], writes = ["output"]}, lhs_semantics = {alignment_bytes = 4 : i64, alignment_contract = "required_precondition", layout = "row_major_contiguous", memory_space = "host", mutability = "read", role = "lhs", shape = [{kind = "dynamic", symbol = "m"}, {kind = "dynamic", symbol = "k"}], source_expression = "A", strides = [{kind = "dynamic", symbol = "k"}, {kind = "static", value = 1 : i64}]}, numerical = {accumulation_dtype = "f32", approximate_math = false, contraction = "allowed", derivation = "explicit_edsl_contract", exception_status = "incoming_not_preserved_postcall_unspecified", infinity = "ieee_no_no_infs_assumption", inplace = false, nan = "preserve_classification_payload_order_unspecified", profile = "explicit-gemm-f32-v1", reassociation = "within_k_reduction", reduction_order = "implementation_defined_within_k", rounding = "nearest_ties_even", signed_zero = "relaxed", subnormals = "ieee_gradual_ftz_daz_forbidden", trapping_exceptions = "unsupported"}, origin = {canonical_callee = "matcore::mdsl::gemm", kind = "explicit_call", version = 1 : i32}, output_semantics = {alignment_bytes = 4 : i64, alignment_contract = "required_precondition", layout = "row_major_contiguous", memory_space = "host", mutability = "write", role = "output", shape = [{kind = "dynamic", symbol = "m"}, {kind = "dynamic", symbol = "n"}], source_expression = "C", strides = [{kind = "dynamic", symbol = "n"}, {kind = "static", value = 1 : i64}]}, policy = {fallback = "error", target = "cpu"}, provenance = {argument_ranges = [{begin = 428 : i64, end = 438 : i64}, {begin = 440 : i64, end = 441 : i64}, {begin = 443 : i64, end = 444 : i64}, {begin = 457 : i64, end = 549 : i64}], call_range = {begin = 419 : i64, end = 550 : i64}, column = 3 : i64, file = "compiler/tests/frontend/gemm_capture.mdsl", kind = "explicit_call", line = 21 : i64, offset = 419 : i64, version = 1 : i32}, rhs_semantics = {alignment_bytes = 4 : i64, alignment_contract = "required_precondition", layout = "row_major_contiguous", memory_space = "host", mutability = "read", role = "rhs", shape = [{kind = "dynamic", symbol = "k"}, {kind = "dynamic", symbol = "n"}], source_expression = "B", strides = [{kind = "dynamic", symbol = "n"}, {kind = "static", value = 1 : i64}]}, semantic_requirements = ["rank2_gemm", "f32_arithmetic", "host_addressable", "synchronous_execution"], site_id = "mc_3c5b6d5e7992fb7b249de44210c6415d", synchronization = "synchronous"} : tensor<?x?xf32>, tensor<?x?xf32> -> tensor<?x?xf32> loc(#loc1)
    %1 = "mdsl.map"(%0) <{domain = {kind = "all", version = 1 : i32}, effects = {read_write = [], reads = ["input"], writes = []}, numerical = {approximate_math = false, domain_application = "active_elements_only", inplace = false, profile = "map-f32-v1", result_identity = "new_functional_value"}, outside_domain = "not_applicable", provenance = {authenticity = "derived_from_producer", column = 3 : i64, file = "compiler/tests/frontend/gemm_capture.mdsl", kind = "derived_semantic_composition", line = 21 : i64, source_anchor = "mc_3c5b6d5e7992fb7b249de44210c6415d", version = 1 : i32}, tensor_contract = {aliasing = "functional_result_no_inplace", alignment_bytes = 4 : i64, alignment_contract = "required_precondition_and_result_contract", dtype = "f32", input_mutability = "read", layout = "row_major_contiguous", memory_space = "host", rank = 2 : i64, result_mutability = "functional_write_once", shape = [{kind = "dynamic", symbol = "m"}, {kind = "dynamic", symbol = "n"}], strides = [{kind = "dynamic", symbol = "n"}, {kind = "static", value = 1 : i64}]}}> ({
    ^bb0(%arg3: f32 loc("compiler/tests/frontend/gemm_capture.mdsl":21:3)):
      %2 = "mdsl.sin"(%arg3) <{numerical = {accuracy = "correctly_rounded_f32", approximate_math = false, exception_status = "postcall_unspecified", infinity = "quiet_nan", nan = "quiet_nan_payload_unspecified", profile = "sin-f32-ieee-v1", rounding = "nearest_ties_even", signed_zero = "preserve", subnormals = "ieee_gradual_ftz_daz_forbidden", trapping_exceptions = "unsupported"}, provenance = {authenticity = "derived_from_producer", column = 3 : i64, file = "compiler/tests/frontend/gemm_capture.mdsl", kind = "derived_elementwise_expression", line = 21 : i64, source_anchor = "mc_3c5b6d5e7992fb7b249de44210c6415d", version = 1 : i32}}> : (f32) -> f32 loc(#loc1)
      "mdsl.yield"(%2) : (f32) -> () loc(#loc1)
    }) : (tensor<?x?xf32>) -> tensor<?x?xf32> loc(#loc1)
    return %1 : tensor<?x?xf32> loc(#loc1)
  } loc(#loc1)
} loc(#loc)
#loc = loc(unknown)
