#ifndef MATCORE_MDSLC_CODEGEN_H
#define MATCORE_MDSLC_CODEGEN_H

#include "../ir/matcore_ir.h"

#include <string>
#include <string_view>
#include <vector>

namespace matcore::mdslc::codegen {

struct Artifacts {
  std::string rewritten_host;
  std::string sites_header;
  std::string stubs_source;
  std::string backend_source;
};

// Internal normalized boundary shared by capture-v0 code generation and the
// Matcore MLIR CPU runtime-dispatch lowering. It deliberately names no private
// CPU implementation: concrete variant selection remains in the runtime
// planner behind matcore_runtime_gemm_f32_v0.
struct RuntimeDispatchBackendEntryV1 {
  std::string site_id;
};

enum class RuntimeDispatchBackendProducerV1 {
  CaptureV0,
  MatcoreMlirCpuV1,
};

// Generates only the C ABI backend translation unit. All entries are
// validated before output is assigned, and duplicate/unsafe site identifiers
// fail closed. CaptureV0 preserves the historical generated bytes; the MLIR
// producer adds an auditable producer marker to the otherwise shared wrapper.
bool generateRuntimeDispatchBackendV1(
    const std::vector<RuntimeDispatchBackendEntryV1> &entries,
    RuntimeDispatchBackendProducerV1 producer, std::string &backend_source,
    std::string &error);

// Generates all four textual artifacts as one transaction. sites_include is
// the quoted-include spelling used by the stubs source. The rewritten host gets
// only global forward declarations before a #line reset, so no user include or
// macro ordering is changed.
bool generate(const ir::Module &module, std::string_view original_source,
              std::string_view sites_include, Artifacts &artifacts,
              std::string &error);

} // namespace matcore::mdslc::codegen

#endif // MATCORE_MDSLC_CODEGEN_H
