cmake_minimum_required(VERSION 3.24)
foreach(required IN ITEMS DRIVER SOURCE OUTPUT_ROOT)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing driver test input ${required}")
  endif()
endforeach()
find_program(driver_readelf NAMES readelf REQUIRED)
if(PROVIDER)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env LC_ALL=C "${driver_readelf}" -d "${PROVIDER}"
    RESULT_VARIABLE status OUTPUT_VARIABLE provider_dynamic ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Cannot inspect configured provider: ${error}")
  endif()
  string(REGEX MATCH "\\(SONAME\\)[^\n]*\\[([^]]+)\\]" provider_soname "${provider_dynamic}")
  if(provider_soname)
    set(provider_needed "${CMAKE_MATCH_1}")
  else()
    set(provider_needed "${PROVIDER}")
  endif()
  get_filename_component(provider_directory "${PROVIDER}" DIRECTORY)
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${OUTPUT_ROOT}/driver-contract-${suffix}")
file(MAKE_DIRECTORY "${root}/physical/deep")
file(READ "${SOURCE}" program)
file(WRITE "${root}/source.mdsl" "${program}")

function(compile name policy)
  execute_process(COMMAND "${DRIVER}" "${root}/source.mdsl"
    --region pipeline --candidate "${policy}" -o "${root}/${name}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "${name} did not compile: ${output}\n${error}")
  endif()
endfunction()
function(execute name)
  execute_process(COMMAND "${root}/${name}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "${name} failed: ${output}\n${error}")
  endif()
  set(last_output "${output}" PARENT_SCOPE)
endfunction()
function(reject name)
  execute_process(COMMAND "${DRIVER}" -o "${root}/${name}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(status EQUAL 0 OR EXISTS "${root}/${name}")
    message(FATAL_ERROR "${name}: invalid invocation published an artifact: ${output}\n${error}")
  endif()
endfunction()

foreach(policy IN ITEMS generated-strict native-strict automatic)
  compile("${policy}" "${policy}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env LC_ALL=C "${driver_readelf}" -d "${root}/${policy}"
    RESULT_VARIABLE status OUTPUT_VARIABLE dynamic ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Cannot inspect issued executable dependencies: ${error}")
  endif()
  if(PROVIDER)
    string(FIND "${dynamic}" "Shared library: [${provider_needed}]" direct_provider)
    string(REGEX MATCH "\\(RUNPATH\\)[^\n]*\\[([^]]+)\\]" search_path "${dynamic}")
    set(search_directories "${CMAKE_MATCH_1}")
    string(REPLACE ":" ";" search_directories "${search_directories}")
    list(FIND search_directories "${provider_directory}" provider_search)
    if(direct_provider EQUAL -1 OR provider_search EQUAL -1)
      message(FATAL_ERROR "Configured provider is not a direct dependency with its runtime search path: ${dynamic}")
    endif()
  elseif(dynamic MATCHES "Shared library: \\[[^]]*[Oo][Pp][Ee][Nn][Bb][Ll][Aa][Ss]")
    message(FATAL_ERROR "Provider-OFF compiler introduced an OpenBLAS dependency: ${dynamic}")
  endif()
  execute("${policy}")
  if(NOT last_output STREQUAL "22 28 49 64 -> 120 156 49 64\n")
    message(FATAL_ERROR "Unexpected successful mathematics: ${last_output}")
  endif()
  execute("${policy}" fail)
  if(NOT last_output STREQUAL "checked failure; first publication and observation retained\n")
    message(FATAL_ERROR "Unexpected failed trace: ${last_output}")
  endif()
endforeach()

# Real parent traversal, not lexical cancellation around a symlink.
string(REPLACE "22 28 49 64 -> 120 156 49 64" "physical source selected" physical "${program}")
file(WRITE "${root}/physical/source.mdsl" "${physical}")
file(CREATE_LINK "${root}/physical/deep" "${root}/link" SYMBOLIC)
execute_process(COMMAND "${DRIVER}" "${root}/link/../source.mdsl"
  --region pipeline -o "${root}/parent-traversal"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Parent-traversal source failed: ${output}\n${error}")
endif()
execute(parent-traversal)
if(NOT last_output STREQUAL "physical source selected\n")
  message(FATAL_ERROR "Driver changed OS input-file selection: ${last_output}")
endif()

file(SHA256 "${root}/generated-strict" original)
execute_process(COMMAND "${DRIVER}" "${root}/source.mdsl" --region pipeline
  -o "${root}/generated-strict" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(SHA256 "${root}/generated-strict" after)
if(status EQUAL 0 OR NOT original STREQUAL after OR NOT error MATCHES "output already exists")
  message(FATAL_ERROR "Existing output was not refused/preserved: ${error}")
endif()
reject(missing-region "${root}/source.mdsl" --region missing)
reject(foreign-input --llvm-input "${root}/source.mdsl" --region pipeline)
reject(unsafe-link-flag "${root}/source.mdsl" --region pipeline -- -Wl,--defsym=forged=0)
reject(source-sanitizer-profile "${root}/source.mdsl" --region pipeline -- -fsanitize=address,undefined)
reject(unknown-candidate "${root}/source.mdsl" --region pipeline --candidate forged)

if(SANITIZED)
  string(PREPEND program "#if !__has_feature(address_sanitizer)\n#error original host must be admitted in the instrumented profile\n#endif\n")
  file(WRITE "${root}/source.mdsl" "${program}")
  compile(instrumented-context generated-strict)
  execute(instrumented-context)
endif()
message(STATUS "Named region compiler: native/generated/automatic math and ordered failure, physical source traversal, no-clobber output, fail-closed driver inputs")
