foreach(required IN ITEMS DRIVER SOURCE OUTPUT_ROOT)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing implementation ownership input ${required}")
  endif()
endforeach()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${OUTPUT_ROOT}/implementation-ownership-${suffix}")
file(MAKE_DIRECTORY "${root}")
configure_file("${SOURCE}" "${root}/source.mdsl" COPYONLY)
foreach(kind IN ITEMS CONTROL PRIVATE_CLEANUP_NAMED PRIVATE_CLEANUP_ASM PRIVATE_HELPER)
  execute_process(COMMAND "${DRIVER}" "${root}/source.mdsl" --region pipeline
    --candidate generated-strict -o "${root}/${kind}" -- "-D${kind}=1"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "${kind} failed source compilation: ${output}\n${error}")
  endif()
  execute_process(COMMAND "${root}/${kind}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "${kind} changed compiler-owned computation/cleanup or the original host: ${status}\n${output}\n${error}")
  endif()
endforeach()
foreach(kind IN ITEMS EXPORTED_FUNCTION EXPORTED_WEAK EXPORTED_DATA EXPORTED_ASM EXPORTED_ALIAS PRIVATE_HELPER_NAMED)
  foreach(mode IN ITEMS executable object)
    set(options)
    if(mode STREQUAL "object")
      list(APPEND options -c)
    endif()
    execute_process(COMMAND "${DRIVER}" "${root}/source.mdsl" --region pipeline
      ${options} -o "${root}/${kind}-${mode}" -- "-D${kind}=1"
      RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    set(reason "original host defines symbol owned by trusted artifact:[ \n]+matcore_closed_host_private_value_abi_v2")
    if(kind STREQUAL "PRIVATE_HELPER_NAMED")
      set(reason "canonical record/enum redeclaration or opaque definition is untrusted")
    endif()
    if(status EQUAL 0 OR EXISTS "${root}/${kind}-${mode}" OR NOT error MATCHES "${reason}")
      message(FATAL_ERROR "${kind}/${mode} did not fail at original-host export ownership: ${output}\n${error}")
    endif()
  endforeach()
endforeach()
message(STATUS "Connected compiler ownership: four generated execution/failure-prefix controls; twelve exported-entry/record object/executable refusals")
