# Fresh-prefix inspection proves absence without deleting an existing package.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(prefix "${BUILD_DIR}/experimental-region-uninstalled-${suffix}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --prefix "${prefix}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Could not inspect installed header boundary: ${output}\n${error}")
endif()
foreach(header IN ITEMS mdsl.h runtime_c.h)
  if(NOT EXISTS "${prefix}/${INSTALL_INCLUDEDIR}/matcore/${header}")
    message(FATAL_ERROR "Legacy installed header missing: ${header}")
  endif()
endforeach()
foreach(path IN ITEMS region.h detail)
  if(EXISTS "${prefix}/${INSTALL_INCLUDEDIR}/matcore/${path}")
    message(FATAL_ERROR "Private region experiment leaked into installed headers: ${path}")
  endif()
endforeach()
message(STATUS "Only established legacy headers are installed; region facade remains private")
