# A private archive is the deliberately unsupported ownership alternative.
# Recognize only exact fixture exits, never any failure as a successful attack.
function(classify_archive_observation ordinary sweep expected required result)
  set(observation invalid)
  if("${sweep}" STREQUAL "${expected}")
    if("${ordinary}" STREQUAL "0")
      set(observation failure-only)
    elseif("${ordinary}" STREQUAL "${expected}")
      set(observation ordinary-path)
    endif()
  elseif(NOT required AND "${ordinary}" STREQUAL "0" AND "${sweep}" STREQUAL "0")
    set(observation not-reproduced)
  endif()
  set("${result}" "${observation}" PARENT_SCOPE)
endfunction()

# Run these tiny classifier falsifiers as part of each existing archive CTest.
# They test the oracle, not the runtime or any particular compiler profile.
function(check_archive_observation ordinary sweep expected required wanted)
  classify_archive_observation("${ordinary}" "${sweep}" "${expected}"
    "${required}" actual)
  if(NOT "${actual}" STREQUAL "${wanted}")
    message(FATAL_ERROR "Archive oracle misclassified (${ordinary},${sweep},${expected},${required}): ${actual}, expected ${wanted}")
  endif()
endfunction()
foreach(exit_code IN ITEMS 71 72)
  foreach(required IN ITEMS ON OFF)
    check_archive_observation(0 "${exit_code}" "${exit_code}" "${required}" failure-only)
    check_archive_observation("${exit_code}" "${exit_code}" "${exit_code}" "${required}" ordinary-path)
    check_archive_observation("${exit_code}" 0 "${exit_code}" "${required}" invalid)
    foreach(unrelated IN ITEMS 1 6 127 "Segmentation fault" "No such file or directory")
      check_archive_observation("${unrelated}" "${exit_code}" "${exit_code}" "${required}" invalid)
      check_archive_observation(0 "${unrelated}" "${exit_code}" "${required}" invalid)
    endforeach()
  endforeach()
  check_archive_observation(0 0 "${exit_code}" ON invalid)
  check_archive_observation(0 0 "${exit_code}" OFF not-reproduced)
endforeach()
check_archive_observation(0 71 72 OFF invalid)
check_archive_observation(0 72 71 OFF invalid)
check_archive_observation(71 72 72 OFF invalid)
check_archive_observation(72 71 71 OFF invalid)
