foreach(required IN ITEMS LIBRARY EXPORTS NM READELF)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing private-library input ${required}")
  endif()
endforeach()
file(READ "${EXPORTS}" specification)
string(REGEX MATCHALL "[\r\n]  [_A-Za-z][_A-Za-z0-9]*;" declarations "${specification}")
set(expected)
foreach(declaration IN LISTS declarations)
  string(STRIP "${declaration}" symbol)
  string(REGEX REPLACE ";$" "" symbol "${symbol}")
  if(NOT symbol STREQUAL "")
    list(APPEND expected "${symbol}")
  endif()
endforeach()
execute_process(COMMAND "${NM}" --dynamic --defined-only --format=just-symbols "${LIBRARY}"
  RESULT_VARIABLE status OUTPUT_VARIABLE actual ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Cannot inspect private library exports: ${error}")
endif()
string(STRIP "${actual}" actual)
string(REPLACE "\n" ";" actual "${actual}")
list(SORT expected)
list(SORT actual)
if(NOT expected OR NOT "${expected}" STREQUAL "${actual}")
  message(FATAL_ERROR "Private library exported interface differs from its exact specification:\nexpected=${expected}\nactual=${actual}")
endif()
execute_process(COMMAND "${READELF}" --dynamic "${LIBRARY}"
  RESULT_VARIABLE status OUTPUT_VARIABLE dynamic ERROR_VARIABLE error)
if(NOT status EQUAL 0 OR NOT dynamic MATCHES "\\(SYMBOLIC\\)" OR
    NOT dynamic MATCHES "Shared library: \\[libmatcore_runtime\\.so\\.0\\]" OR
    dynamic MATCHES "Shared library: \\[lib(openblas|LLVM|MLIR)")
  message(FATAL_ERROR "Private library lacks local binding or duplicates provider/compiler ownership: ${dynamic}\n${error}")
endif()
list(LENGTH actual count)
message(STATUS "Private runtime: exactly ${count} declared exports; local binding; canonical Runtime provider owner")
